### ISSUE TITLE
Compilation error in MSVC using C++20

### ISSUE THREAD

**Issue by andrewcorrigan** [bluescarni/obake#143]
Similar to https://github.com/bluescarni/mppp/issues/291, I am attempting to compile using MSVC in C++20 mode.  I just encountered the following error:

```
\obake\include\obake/polynomials/polynomial.hpp(204): error C2101: '&' on constant
```
in reference to:
```
        constexpr int arr[] = {1};

        // Create and add a new term.
        retval.add_term(series_key_t<T>(&arr[0], &arr[0] + 1), 1);
```

I modified the code as follows, in which case compilation succeeded:
```
        static constexpr int arr[] = {1};

        // Create and add a new term.
        retval.add_term(series_key_t<T>(&arr[0], &arr[0] + 1), 1);
```

I am still on an older version of Obake 0.6.0.  However, the current version of Obake has the same snippet of code above.

Would it make sense to do a PR with the modification above?

**Comment by bluescarni** [comment]
@andrewcorrigan would it be possible for you to give a shot to the latest version?

**Comment by andrewcorrigan** [comment]
I tested it with the latest version resulting in the same error as above when compiling in C++20 mode:
```
9>Building Custom Rule C:/Users/developer/Downloads/obake-0.7.0/test/CMakeLists.txt
9>exceptions.cpp
6>audi_01.cpp
6>C:\Users\developer\Downloads\obake-0.7.0\include\obake/polynomials/polynomial.hpp(222): error C2101: '&' on constant
```

From this discussion on stackoverflow [1], I believe that the modification proposed above is an appropriate workaround.

[1] https://stackoverflow.com/questions/28614591/how-to-initialize-a-constexpr-reference
